tldrapp/models/home.py
from sqlalchemy import event
from hashids import Hashids
from datetime import datetime

from .custom_types import Json

from .. import db


class Summary(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    bullets = db.Column(Json)
    highlighted_text = db.Column(Json)
    source_url = db.Column(db.String(80))
    date_added = db.Column(db.DateTime)
    url = db.Column(db.String(80), unique=True)
    type = db.Column('type', db.String(50))

    # Set a discriminator so that summary items can be distinguished from
    # items derived from subclasses in queries
    __mapper_args__ = {'polymorphic_on': type,
                       'polymorphic_identity': 'summary'}

    def __init__(self,
                 bullets,
                 highlighted_text,
                 source_url='',
                 date_added=None):
        self.bullets = bullets
        self.highlighted_text = highlighted_text
        self.source_url = source_url
        if not date_added:
            date_added = datetime.utcnow()
        self.date_added = date_added

    def __repr__(self):
        return '<Summary {0}>'.format(self.url)


@event.listens_for(Summary, "after_insert")
def update_url_hash(mapper, connection, target):
    summary_table = mapper.local_table
    hasher = Hashids(min_length=5)
    connection.execute(
        summary_table.update().
        values(url=hasher.encode(target.id)).
        where(summary_table.c.id == target.id)
    )

tldrapp/forms/home.py
from flask_wtf import Form
from wtforms import StringField, FloatField, SelectField
from wtforms.validators import NumberRange, InputRequired
from wtforms.widgets import TextArea
from ..processing.summarizer import algorithms


class SummarizerForm(Form):
    text = StringField(
        'Text or URL to summarize:',
        validators=[InputRequired()],
        widget=TextArea())

    algorithm = SelectField(
        'Algorithm:',
        validators=[InputRequired()],
        choices=zip(algorithms.names, algorithms.names))

    length = FloatField(
        'Length (# of sentences or % of original text):',
        validators=[NumberRange(min=0)],
        default=0.2)

tldrapp/views/home.py
import os

from flask import Blueprint, render_template, request, flash, url_for

from .. import db
from ..models.home import Summary
from ..forms.home import SummarizerForm
from ..processing.summarizer import Summarizer
from ..helpers import flash_errors
from ..processing.newsbot import NewsBot

home = Blueprint('home', __name__)


@home.route('/', methods=['GET', 'POST'])
def index():
    summary = None
    url = ''

    form = SummarizerForm(request.form)

    if request.method == "POST" and form.validate():
        summary = Summarizer(form.text.data, form.algorithm.data, form.length.data)
        if summary.error:
            flash(summary.error)
        else:
            source_url = form.text.data if form.text.data.startswith(('http://', 'https://')) else ''
            summary_db_entry = Summary(
                summary.bullets,
                summary.highlighted_text,
                source_url=source_url)
            db.session.add(summary_db_entry)
            db.session.commit()

            url_hash = summary_db_entry.url
            url = os.path.join(request.url, url_for('home.summary_entry', url_hash=url_hash)[1:])

    flash_errors(form)

    return render_template(
        'home/index.html',
        form=form,
        summary=summary,
        url=url
    )


@home.route('/s/<url_hash>')
def summary_entry(url_hash):
    summary = Summary.query.filter_by(url=url_hash).first_or_404()
    source_url = summary.source_url

    return render_template(
        'home/summary.html',
        summary=summary,
        source_url=source_url
    )

@home.route('/about')
@home.route('/about/')
def about():
    return render_template('home/about.html')

tldrapp/templates/home.html
{% extends "layout.html" %}
{% set active_page = "home" %}
{% block content %}
    <div class="panel panel-info">
        <div class="panel-heading">
            <h1 class="panel-title">Automatic Text Summarizer <small>by Jai Juneja</small></h1>
        </div>
        <div class="panel-body">
            <form action="" method=post>
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.text.label }}
                    {{ form.text(rows=5, class_='form-control') }}
                </div>
                <div class="form-group">
                    {{ form.algorithm.label }}
                    {{ form.algorithm(class_='form-control') }}
                </div>
                <div class="form-group">
                    {{ form.length.label }}
                    {{ form.length(class_='form-control') }}
                </div>
                <button class="btn btn-info" type=submit value="Summarize">Summarize</button>
            </form>
        </div>
    </div>

    {% if summary %}
        <div id="summary">
            <div class="well clearfix">
                <div class="col-md-3">
                    <h3 class="share-link">Share Link</h3>
                </div>
                <div class="form-group col-md-9">
                    <input id="summary-link" class="form-control" value="sometext"
                           onclick="this.setSelectionRange(0, this.value.length)">
                </div>
            </div>
            <div class="well">
                {% include 'includes/summary_composite.html' %}
            </div>
        </div>
    {% endif %}

{% endblock %}

tldrapp/templates/layout.html
{% set navigation_bar = [
    ('/', 'home', 'Home'),
    ('/quickipedia', 'quickipedia', 'Quickipedia'),
    ('/news', 'news', 'News'),
    ('/about', 'about', 'About'),
] -%}
{% set active_page = active_page|default('index') -%}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=1">
    <title>{% block title %}{% endblock %} - ZipRead</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>
<body>
    <div class="container">
        <header>
            {% block header %}
            <nav class="navbar navbar-default">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
{#                        <a class="navbar-brand" href="/">TL;DR Summarizer</a>#}
                        <a href="{% block logo_href %}{{ url_for('home.index') }}{% endblock %}">
                            <img src="{% block logo %}{{ url_for('static', filename='images/logo.png') }}{% endblock %}"
                             class="logo navbar-brand">
                        </a>
                    </div>

                        <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            {% for href, id, text in navigation_bar %}
                                <li{% if id == active_page %} class="active"{% endif %}>
                                    <a href="{{ href|e }}">{{ text|e }}</a>
                                </li>
                            {% endfor %}
                        </ul>

                        {% include 'news/nav_search.html' %}
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
            </nav>
            {% endblock %}
        </header>
        {% include 'includes/errors.html' %}
        {% block content %}{% endblock %}
    </div>

    <footer class="footer">
        {% block footer %}
            <div class="container">
                <p class="text-muted">Developed by <a href="http://www.jaijuneja.com">Jai Juneja</a></p>
            </div>
        {% endblock %}
    </footer>

    {% block js_scripts %}
        <script type="text/javascript" src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.js') }}" ></script>
    {% endblock %}
</body>
</html>