tldrapp/models/news.py
import flask.ext.whooshalchemy as whooshalchemy

from whoosh.analysis import SimpleAnalyzer
from sqlalchemy import event
from hashids import Hashids
from pytldr.nlp.tokenizer import Tokenizer

from .home import Summary

from .. import app, db


class NewsSource(db.Model):
    __searchable__ = ['name']
    __analyzer__ = SimpleAnalyzer()

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(32))
    slug = db.Column(db.String(32))
    feed_url = db.Column(db.String(80))
    image_path = db.Column(db.String(80))

    def __init__(self, name, image_path=''):
        self.name = name
        self.slug = Tokenizer().strip_all_punctuation(name.lower()).replace(' ', '_')
        if not image_path:
            self.image_path = '/static/images/news/sources/{0}.png'.format(self.slug)
        else:
            self.image_path = image_path

    def __repr__(self):
        return '<NewsSource {0}>'.format(self.name)


class NewsCategory(db.Model):

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(32))
    slug = db.Column(db.String(32))

    def __init__(self, name):
        self.name = name

        tokenizer = Tokenizer()
        slug = tokenizer.strip_all_punctuation(name.lower())
        self.slug = slug.replace(' ', '_')

    def __repr__(self):
        return '<NewsCategory {0}>'.format(self.name)


class NewsSummary(Summary):
    __searchable__ = ['bullets']
    __analyzer__ = SimpleAnalyzer()

    __mapper_args__ = {'polymorphic_identity': 'newssummary',
                       'inherit_condition': (id == Summary.id)}

    title = db.Column(db.String)
    pub_date = db.Column(db.DateTime)
    image_path = db.Column(db.String(80))

    news_source_id = db.Column(db.Integer, db.ForeignKey('news_source.id'))
    news_source = db.relationship('NewsSource', backref=db.backref('summaries', lazy='dynamic'))

    news_category_id = db.Column(db.Integer, db.ForeignKey('news_category.id'))
    news_category = db.relationship('NewsCategory', backref=db.backref('summaries', lazy='dynamic'))

    def __init__(self,
                 title,
                 bullets,
                 highlighted_text,
                 news_source,
                 source_url,
                 news_category,
                 date_added=None,
                 pub_date=None,
                 image_path='',
                 ):
        super(NewsSummary, self).__init__(
            bullets,
            highlighted_text,
            source_url=source_url,
            date_added=date_added)

        self.title = title
        self.news_source = news_source
        self.news_category = news_category
        self.pub_date = pub_date
        if image_path:
            self.image_path = image_path
        else:
            self.image_path = news_source.image_path

    def __repr__(self):
        return '<NewsSummary {0}>'.format(self.title)


@event.listens_for(NewsSummary, "after_insert")
def update_url(mapper, connection, target):
    url_max_length = 30
    news_summary_table = mapper.local_table

    tokenizer = Tokenizer()
    title_clean = tokenizer.strip_all_punctuation(target.title.lower())
    title_clean = tokenizer.remove_stopwords(title_clean) if len(title_clean) > url_max_length else title_clean
    while len(title_clean) > url_max_length:
        title_clean = ' '.join(title_clean.split(' ')[:-1])  # Remove last word from title
    title_clean = title_clean.replace(' ', '-')

    url_hash = Hashids(min_length=4).encode(target.id)
    url = title_clean + '-' + url_hash

    connection.execute(
        news_summary_table.update().values(url=url).where(news_summary_table.c.id == target.id)
    )

# Add the summary table to the search index
whooshalchemy.whoosh_index(app, NewsSummary)
whooshalchemy.whoosh_index(app, NewsSource)

tldrapp/forms/news.py
from flask_wtf import Form
from wtforms import StringField
from wtforms.validators import DataRequired


class SearchForm(Form):
    search = StringField('Search News:', validators=[DataRequired()])

tldrapp/views/news.py
from flask import g, Blueprint, render_template, request, redirect, url_for, abort
from ..helpers import flash_errors
from ..models.news import NewsSummary, NewsCategory, NewsSource
from ..forms.news import SearchForm
from ..cache import cache
from .. import app
from ..processing.newsrank import rank_news
from config import MAX_SEARCH_RESULTS

news = Blueprint('news', __name__)

@app.before_request
def before_request():
    g.search_form = SearchForm()


@cache.memoize(3600)
@news.route('/')
@news.route('/page/<int:page>')
def index(page=1):
    results_per_page = app.config['NEWS_PER_PAGE']
    results = NewsSummary.query\
        .order_by(NewsSummary.pub_date.desc())\
        .paginate(page, results_per_page, False).items

    sidebar = get_hot_sidebar('', '')
    categories, sources = get_bottom_nav()

    template = 'news/index.html' if page == 1 else 'news/news_items.html'
    return render_template(template, results=results, sidebar=sidebar, page=page, categories=categories, sources=sources)


@cache.memoize(3600)
@news.route('/category/<category>/')
@news.route('/category/<category>/page/<int:page>')
def category_page(category, page=1):
    results_per_page = app.config['NEWS_PER_PAGE']
    results = NewsSummary.query.join(NewsCategory)\
        .filter(NewsCategory.slug == category)\
        .order_by(NewsSummary.pub_date.desc())\
        .paginate(page, results_per_page, False).items

    if not results:
        abort(404)

    sidebar = get_hot_sidebar('category', category)
    categories, sources = get_bottom_nav()

    template = 'news/index.html' if page == 1 else 'news/news_items.html'
    return render_template(template, results=results, sidebar=sidebar, page=page, categories=categories, sources=sources)


@cache.memoize(3600)
@news.route('/source/<source>/')
@news.route('/source/<source>/page/<int:page>')
def source_page(source, page=1):
    results_per_page = app.config['NEWS_PER_PAGE']
    results = NewsSummary.query.join(NewsSource)\
        .filter(NewsSource.slug == source)\
        .order_by(NewsSummary.pub_date.desc())\
        .paginate(page, results_per_page, False).items

    if not results:
        abort(404)

    sidebar = get_hot_sidebar('source', source)
    categories, sources = get_bottom_nav()

    template = 'news/index.html' if page == 1 else 'news/news_items.html'
    return render_template(template, results=results, sidebar=sidebar, page=page, categories=categories, sources=sources)


@news.route('/<url_hash>')
def news_entry(url_hash):
    summary = NewsSummary.query.filter_by(url=url_hash).first_or_404()
    source_url = summary.source_url

    return render_template(
        'news/entry.html',
        summary=summary,
        source_url=source_url
    )


@news.route('/search', methods=['GET', 'POST'])
def search():

    form = SearchForm(request.form)

    if request.method == 'POST' and form.validate():
        return redirect(url_for('news.search_results', query=form.search.data))

    flash_errors(form)
    return render_template('news/search.html', form=form)


@news.route('/search/<query>')
def search_results(query):
    results = NewsSummary.query.whoosh_search(query, MAX_SEARCH_RESULTS).all()
    return render_template('news/search_results.html',
                           query=query,
                           results=results)


@cache.memoize(3600)
def get_hot_sidebar(category_type, category_name, num_input_articles=500, num_output_articles=10):
    if category_type == 'category':
        articles = NewsSummary.query.join(NewsCategory)\
            .filter(NewsCategory.slug == category_name)\
            .order_by(NewsSummary.pub_date.desc()).limit(num_input_articles).all()
    elif category_type == 'source':
        articles = NewsSummary.query.join(NewsSource)\
            .filter(NewsSource.slug == category_name)\
            .order_by(NewsSummary.pub_date.desc()).limit(num_input_articles).all()
    else:
        articles = NewsSummary.query.order_by(NewsSummary.pub_date.desc()).limit(num_input_articles).all()

    article_titles = [article.title for article in articles]

    # Replace 'None' article titles with empty string
    for i, _ in enumerate(article_titles):
        article_titles[i] = '' if not article_titles[i] else article_titles[i]

    top_articles = rank_news(article_titles, length=num_output_articles)

    return [articles[i] for i in top_articles]


@cache.memoize(3600)
def get_bottom_nav():
    categories = NewsCategory.query.order_by(NewsCategory.name.asc()).all()
    sources = NewsSource.query.order_by(NewsSource.name.asc()).all()
    return categories, sources

tldrapp/templates/news/entry.html
{% extends "news/layout.html" %}
{% block title %}View Summary{% endblock %}

{% block content %}
    {% if source_url %}
        <div class="well">
            <a href="/news/source/{{ summary.news_source.slug }}"><button type="button" class="btn news-button {{ summary.news_source.slug }}">{{ summary.news_source.name }}</button></a>
            <a href="/news/category/{{ summary.news_category.slug }}"><button type="button" class="btn news-button btn-default">{{ summary.news_category.name }}</button></a>
            &nbsp; View the original article <a href="{{ source_url }}">here</a>.
        </div>
    {% endif %}
    <div class="panel panel-info">
        <div class="panel-heading">
            <h1 class="panel-title">Summary: {{ summary.title }}</h1>
        </div>
        {% if summary.pub_date %}
            <div class="panel-news-source clearfix">
                Published: {{ pretty_date(summary.pub_date) }}
            </div>
        {% endif %}
        <div class="panel-body">
            {% include 'includes/summary_composite.html' %}
        </div>
    </div>
{% endblock %}

{% block js_scripts %}
    {{ super() }}
    <script type="text/javascript" src="{{ url_for('static', filename='js/summary.js') }}" ></script>
{% endblock %}

tldrapp/templates/news/index.html
{% extends "news/layout.html" %}
{% block title %}News{% endblock %}

{% block content %}

    <div class="news-wrapper">
        <div class="well col-lg-12">
            <h2>
                This week's top news<br>
                <small>delivered in bite-sized chunks</small>
            </h2>
        </div>

        <div class="news-main-content clearfix col-lg-9">
            {% if results %}
            <div class="js-infinite-layout">
                {% include 'news/news_items.html' %}
                <div class="js-infinite-navigation">
                    <a href="{{ request.url }}page/{{ page + 1 }}"></a>
                </div>
            </div>

            {% else %}
                <p class="alert alert-info">
                    No news to show.
                </p>
            {% endif %}

        </div>

        <div class="news-sidebar col-lg-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h1 class="panel-title">Top Stories</h1>
                </div>
                <div class="panel-body">
                    {% include 'news/sidebar.html' %}
                </div>
            </div>
        </div>
    </div>

    {% include 'news/nav_bottom.html' %}

{% endblock %}

{% block js_scripts %}
    {{ super() }}
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery.infinitescroll.min.js') }}" ></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/news.js') }}" ></script>
{% endblock %}

tldrapp/templates/news/layout.html
{% extends "layout.html" %}
{% set active_page = "news" %}
{% block logo_href %}{{ url_for('news.index') }}{% endblock %}
{% block logo %}{{ url_for('static', filename='images/news-logo.png') }}{% endblock %}

tldrapp/templates/news/nav_bottom.html
<nav class="navbar navbar-default navbar-fixed-bottom bottom-menu">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="navbar-brand filter-news">Filter News</div>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">By Category <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        {% for category in categories %}
                            <li><a href="/news/category/{{ category.slug }}">{{ category.name }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">By Source <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        {% for source in sources %}
                            <li><a href="/news/source/{{ source.slug }}">{{ source.name }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

tldrapp/templates/news/nav_search.html
<form class="navbar-form pull-right" method="post" name="search" action="{{ url_for('news.search') }}">
    {{ g.search_form.hidden_tag() }}
    <div class="form-group">
        {{ g.search_form.search(placeholder='Search news...', class_='form-control search-query') }}
    </div>
</form>

tldrapp/templates/news/news.html
{% extends "layout.html" %}
{% set active_page = "news" %}
{% block title %}News{% endblock %}

{% block content %}

    <div class="news-wrapper">
        <div class="well col-lg-12">
            <h2>
                This week's top news<br>
                <small>from your favourite sources</small>
            </h2>
        </div>

        <div class="news-main-content clearfix col-lg-9">
            {% for i in range(8) %}
            <div class="col-lg-6">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h1 class="panel-title">News Title</h1>
                    </div>
                    <div class="panel-news-source">
                        Source: BBC News
                    </div>
                    <div class="panel-body">
                        Circular image here (article image or source image?). Like in carousel example.
                        <ul>
                            {% for k in range(5) %}
                            <li>News content.</li>
                            {% endfor %}
                        </ul>
                        <div class="read-more-news">
                            <button class="btn btn-info news-read-more">Read More</button>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

        <div class="news-sidebar col-lg-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h1 class="panel-title">New Stories</h1>
                </div>
                <div class="panel-body">
                    Hot articles from the past week.
                </div>
            </div>
        </div>
    </div>

{% endblock %}

tldrapp/templates/news/news_item.html
<div class="col-lg-12 js-infinite-item">
    <div class="panel panel-info">
        <div class="panel-heading">
            <a href="/news/{{ summary.url }}"><h1 class="panel-title">{{ summary.title }}</h1></a>
        </div>
        <div class="panel-news-source clearfix">
            <div class="float-left">
                <a href="/news/source/{{ summary.news_source.slug }}"><button type="button" class="btn news-button {{ summary.news_source.slug }}">{{ summary.news_source.name }}</button></a>
                <a href="/news/category/{{ summary.news_category.slug }}"><button type="button" class="btn news-button btn-default">{{ summary.news_category.name }}</button></a>
            </div>
            <div class="float-left pub-date">
                {{ pretty_date(summary.pub_date) }}
            </div>
        </div>
        <div class="panel-body">
            <div class="news-image"
                 style="background-image: url('{{ summary.image_path }}');">
             </div>
            <ul class="summary-list">
                {% set counter = [0] %}
                {% for sentence in summary.bullets %}
                    {% set _ = counter.append(counter.pop() + 1) %}
                    {% if counter[0] <= 5 %}
                        <li>{{ sentence }}</li>
                    {% endif %}
                {% endfor %}
            </ul>
            <div class="more-news">
                <div class="hidden">
                    <ul class="summary-list read-more-ul">
                        {% set counter = [0] %}
                        {% for sentence in summary.bullets %}
                            {% set _ = counter.append(counter.pop() + 1) %}
                            {% if counter[0] > 5 %}
                                <li>{{ sentence }}</li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
                {% if counter[0] > 5 %}
                    <div class="read-more-news">
                        <a class="btn btn-info news-read-more readMore" href="#" onclick="return false;">Read More</a>
                        <a class="btn btn-info news-read-more readLess hidden" href="#" onclick="return false;">Read Less</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

tldrapp/templates/news/news_items.html
{% for summary in results %}
    {% include 'news/news_item.html' %}
{% endfor %}

tldrapp/templates/news/search.html
{% extends "news/layout.html" %}
{% block title %}News Search{% endblock %}

{% block content %}
    <div class="panel panel-info">
        <div class="panel-heading">
            <h1 class="panel-title">News Search</h1>
        </div>
        <div class="panel-body">

            <form action="" method="post">
                {{ form.hidden_tag() }}
                <div class="form-group col-sm-9">
                    {{ form.search(class_='form-control', placeholder='Search news summaries...') }}
                </div>
                <div class="col-sm-3">
                    <button class="btn btn-info form-control" type="submit" value="SearchNews">Search</button>
                </div>
            </form>

        </div>
    </div>
{% endblock %}

tldrapp/templates/news/search_results.html
{% extends "news/layout.html" %}
{% block title %}News Search{% endblock %}

{% block content %}
    <div class="well">
        Showing results for "{{ query }}".
    </div>
    <ul>
    {% for result in results %}
        <li>
            <a href="../{{ result.url }}">{{ result.title }}</a>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

tldrapp/templates/news/sidebar.html
<div class="list-group sidebar-group">
    {% for item in sidebar %}
        <a href="/news/{{ item.url }}" class="list-group-item sidebar-item">{{ item.title }}</a>
    {% endfor %}
</div>